/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BaoHanhBUS;
import DTO.BaoHanhDTO;
import DTO.ChiTietBaoHanhDTO;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.KhachHangDTO;
import DTO.LanBaoHanhDTO;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THANH NHAN
 */
public class BaoHanhDienThoaiUI extends javax.swing.JPanel {
    BaoHanhBUS bus=new BaoHanhBUS();
    /**
     * Creates new form PhieuNhapUI
     */
    public BaoHanhDienThoaiUI() {
        com.formdev.flatlaf.intellijthemes.FlatNordIJTheme.setup();
    initComponents();
        
        customTable();
        jTabbedPane1.remove(1); // xóa tab thứ 2
        veBangBaoHanh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thembaohanh = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmabaohanh = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtngaylap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtmanhanvien = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttenkh = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        bangchitietbaohanh1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        txtimei = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtmakhachhang = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        baohanh = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txttimmabaohanh = new javax.swing.JTextField();
        btntimmabaohanh = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bangchitietbaohanh2 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txttinhtrang = new javax.swing.JTextField();
        txtxuly = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        banglanbaohanh = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        btnxuatexcel1 = new javax.swing.JButton();
        btnxuatexcel2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangbaohanh = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        bangchitietbaohanh = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        cbtimkiem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datedenngay = new com.toedter.calendar.JDateChooser();
        datetungay = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        btnreset1 = new javax.swing.JButton();
        btnreset2 = new javax.swing.JButton();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        cancelButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(151, 180, 198));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BẢO HÀNH ĐIỆN THOẠI");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(148, 148, 148))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel11.setText("Mã bảo hành");

        txtmabaohanh.setBackground(new java.awt.Color(244, 244, 214));
        txtmabaohanh.setForeground(new java.awt.Color(0, 0, 0));
        txtmabaohanh.setText("\n");
        txtmabaohanh.setDragEnabled(true);
        txtmabaohanh.setEnabled(false);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel12.setText("Mã hóa đơn");

        txtngaylap.setBackground(new java.awt.Color(244, 244, 214));
        txtngaylap.setForeground(new java.awt.Color(0, 0, 0));
        txtngaylap.setText("\n");
        txtngaylap.setEnabled(false);
        txtngaylap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaylapActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel13.setText("Ngày lập");

        txtmahoadon.setBackground(new java.awt.Color(244, 244, 214));
        txtmahoadon.setForeground(new java.awt.Color(0, 0, 0));
        txtmahoadon.setText("\n");
        txtmahoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahoadonActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel14.setText("Tên khách");

        txtmanhanvien.setBackground(new java.awt.Color(244, 244, 214));
        txtmanhanvien.setForeground(new java.awt.Color(0, 0, 0));
        txtmanhanvien.setText("\n");
        txtmanhanvien.setEnabled(false);
        txtmanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanhanvienActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel15.setText("Thông tin khách hàng");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel16.setText("Nhân viên");

        txttenkh.setBackground(new java.awt.Color(244, 244, 214));
        txttenkh.setForeground(new java.awt.Color(0, 0, 0));
        txttenkh.setText("\n");
        txttenkh.setEnabled(false);
        txttenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenkhActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel17.setText("SĐT ");

        txtsdt.setBackground(new java.awt.Color(244, 244, 214));
        txtsdt.setForeground(new java.awt.Color(0, 0, 0));
        txtsdt.setText("\n");
        txtsdt.setEnabled(false);
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel18.setText("Email");

        txtemail.setBackground(new java.awt.Color(244, 244, 214));
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.setText("\n");
        txtemail.setEnabled(false);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        bangchitietbaohanh1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "IMEI", "Mã sản phẩm", "Tên sản phẩm", "Thời hạn bảo hành", "Hết hạn"
            }
        ));
        bangchitietbaohanh1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bangchitietbaohanh1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(bangchitietbaohanh1);

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel19.setText("IMEI");

        txtimei.setForeground(new java.awt.Color(0, 0, 0));
        txtimei.setText("\n");
        txtimei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimeiActionPerformed(evt);
            }
        });

        jButton2.setText("Lưu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel20.setText("Mã khách hàng");

        txtmakhachhang.setBackground(new java.awt.Color(244, 244, 214));
        txtmakhachhang.setForeground(new java.awt.Color(0, 0, 0));
        txtmakhachhang.setText("\n");
        txtmakhachhang.setEnabled(false);
        txtmakhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmakhachhangActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 255, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Lưu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(215, 215, 215)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtmakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel16))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtmabaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtmahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addComponent(jButton3)))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmabaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtmahoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmakhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout thembaohanhLayout = new javax.swing.GroupLayout(thembaohanh.getContentPane());
        thembaohanh.getContentPane().setLayout(thembaohanhLayout);
        thembaohanhLayout.setHorizontalGroup(
            thembaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thembaohanhLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thembaohanhLayout.setVerticalGroup(
            thembaohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thembaohanhLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setText("Bảo hành");

        jLabel22.setText("Mã bảo hành");

        btntimmabaohanh.setText("Tìm");
        btntimmabaohanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimmabaohanhActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Danh sách sản phẩm bảo hành");

        bangchitietbaohanh2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "IMEI", "Ngày hết bảo hành"
            }
        ));
        bangchitietbaohanh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangchitietbaohanh2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(bangchitietbaohanh2);

        jLabel24.setText("Tình trạng");

        jLabel25.setText("Xử lý");

        banglanbaohanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã ", "Ngày nhận", "Ngày trả", "Tình trang", "Xử lý", "Trạng thái"
            }
        ));
        banglanbaohanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banglanbaohanhMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(banglanbaohanh);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Lich sử bảo hành");

        jButton7.setText("Hoành thành");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("Tạo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout baohanhLayout = new javax.swing.GroupLayout(baohanh.getContentPane());
        baohanh.getContentPane().setLayout(baohanhLayout);
        baohanhLayout.setHorizontalGroup(
            baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baohanhLayout.createSequentialGroup()
                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baohanhLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel21))
                    .addGroup(baohanhLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimmabaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntimmabaohanh))
                    .addGroup(baohanhLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel23))
                    .addGroup(baohanhLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(baohanhLayout.createSequentialGroup()
                                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttinhtrang)
                                    .addComponent(txtxuly, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                            .addGroup(baohanhLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(baohanhLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel26)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        baohanhLayout.setVerticalGroup(
            baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baohanhLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addGap(21, 21, 21)
                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txttimmabaohanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimmabaohanh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txttinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txtxuly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(baohanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(5, 5, 5)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1710, 1080));

        jPanel1.setPreferredSize(new java.awt.Dimension(1710, 1080));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1710, 180));

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(505, 100));
        jToolBar1.add(jSeparator1);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        jButton4.setText("Xuất PDF");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        btnxuatexcel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnxuatexcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel (2).png"))); // NOI18N
        btnxuatexcel1.setText("Xuất Excel");
        btnxuatexcel1.setFocusable(false);
        btnxuatexcel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuatexcel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuatexcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatexcel1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnxuatexcel1);

        btnxuatexcel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnxuatexcel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel (2).png"))); // NOI18N
        btnxuatexcel2.setText("Xuất Excel tất cả");
        btnxuatexcel2.setFocusable(false);
        btnxuatexcel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuatexcel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuatexcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatexcel2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnxuatexcel2);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        jButton1.setText("Thêm bảo hành");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu-burger (2).png"))); // NOI18N
        jButton6.setText("Bảo hành");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jPanel4.setBackground(new java.awt.Color(18, 77, 122));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 41)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DỊCH VỤ BẢO HÀNH ĐIỆN THOẠI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(1198, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(640, 640, 640)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 970, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel8.setPreferredSize(new java.awt.Dimension(1710, 1080));

        bangbaohanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã bảo hành", "Mã khách hàng", "Mã nhân viên", "Ngày lập"
            }
        ));
        bangbaohanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangbaohanhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bangbaohanh);

        bangchitietbaohanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "IMEI", "Ngày hết bảo hành"
            }
        ));
        jScrollPane3.setViewportView(bangchitietbaohanh);
        if (bangchitietbaohanh.getColumnModel().getColumnCount() > 0) {
            bangchitietbaohanh.getColumnModel().getColumn(0).setMaxWidth(60);
            bangchitietbaohanh.getColumnModel().getColumn(1).setPreferredWidth(40);
            bangchitietbaohanh.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Bảng bảo hành");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kiếm tra bảo hành", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(820, 90));

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnreset.setText("Tìm");
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        cbtimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbtimkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã bảo hành", "Mã nhân viên", "Mã khách hàng" }));

        jLabel1.setText("Từ ngày");

        jLabel9.setText("Đén ngày");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datetungay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datedenngay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(cbtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(datedenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datetungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Bảng chi tiết bảo hành");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 422, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thời hạn bảo hành ", jPanel9);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên máy", "Mã IMEI", "Ngày hẹn"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Tên máy:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Mã IMEI:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Ngày từ:");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Ngày đến:");

        btnreset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnreset1.setText("Làm mới");
        btnreset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        btnreset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnreset2.setText("Tìm");
        btnreset2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(btnreset2)
                            .addGap(26, 26, 26)
                            .addComponent(btnreset1))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(jTextField2)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnreset1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreset2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bảo hành máy", jPanel10);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void customTable() {
        
        java.awt.Font tableFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18);
        bangbaohanh.setFont(tableFont);
        bangbaohanh.setRowHeight(30);

        bangbaohanh.getTableHeader().setOpaque(false);
        bangbaohanh.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        bangchitietbaohanh.setFont(tableFont);
        bangchitietbaohanh.setRowHeight(30);

        bangchitietbaohanh.getTableHeader().setOpaque(false);
        bangchitietbaohanh.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            bangchitietbaohanh.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            bangbaohanh.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    private void resizeColumnWidth(javax.swing.JTable table) {
        final javax.swing.table.TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 70; 
            for (int row = 0; row < table.getRowCount(); row++) {
                javax.swing.table.TableCellRenderer renderer = table.getCellRenderer(row, column);
                java.awt.Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 15, width);
            }
            if (width > 400) {
                width = 400; 
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    public void veBangBaoHanh() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) bangbaohanh.getModel();
        model.setRowCount(0);
        int i=1;
        for (DTO.BaoHanhDTO bh : bus.getDS()) {
            model.addRow(new Object[]{i++,bh.getMaBH(), bh.getMaKH(), bh.getMaNV(),bh.getNgayLap()});
        }
    }
    public void veBangBaoHanh(ArrayList<BaoHanhDTO> ds) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) bangbaohanh.getModel();
        model.setRowCount(0);
        int i=1;
        for (DTO.BaoHanhDTO bh : ds) {
            model.addRow(new Object[]{i++,bh.getMaBH(), bh.getMaKH(), bh.getMaNV(),bh.getNgayLap()});
        }
    }
    public void veBangChiTietBaoHang(String mabh){
         javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) bangchitietbaohanh.getModel();
         model.setRowCount(0);
         int i=1;
         for(ChiTietBaoHanhDTO ctbh :bus.selectCTBHByMaBH(mabh)){
             model.addRow(new Object[]{i++,ctbh.getIMEI(), ctbh.getNgay() , ctbh.getTinhTrang() , ctbh.getXuLy()});
         }
    }

    
    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
    String chucnang = cbtimkiem.getSelectedItem().toString();
        String key = txttimkiem.getText().trim();

        ArrayList<BaoHanhDTO> ds = bus.getDS();

        if(!key.equals("")){
            switch (chucnang) {
                case "Mã bảo hành" -> ds = bus.timKiemBHByMaBH(key);
                case "Mã khách hàng" -> ds = bus.timKiemBHByMaKH(key);
                default -> ds = bus.timKiemBHByMaNV(key);
            }
        }

        LocalDate tu = LocalDate.MIN;
        LocalDate den = LocalDate.MAX;

        if(datetungay.getDate() != null){
            tu = bus.chuyenDateThanhLocalDate(datetungay.getDate());
        }

        if(datedenngay.getDate() != null){
            den = bus.chuyenDateThanhLocalDate(datedenngay.getDate());
        }

        ds = bus.timKiemBHByDate(ds, tu, den);

        veBangBaoHanh(ds);
    }//GEN-LAST:event_btnresetActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

    }//GEN-LAST:event_jButton4MouseClicked

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void btnreset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreset2ActionPerformed

    private void bangbaohanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangbaohanhMouseClicked
        // TODO add your handling code here:
        int row;
        row=bangbaohanh.getSelectedRow();
        if(row!=-1){
            String mabh=bangbaohanh.getValueAt(row, 1).toString();
            veBangChiTietBaoHang(mabh);
        }
    }//GEN-LAST:event_bangbaohanhMouseClicked

    private void btnxuatexcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatexcel1ActionPerformed
        // TODO add your handling code here:
        int row=bangbaohanh.getSelectedRow();
        if(row!=-1){
            String mabh=bangbaohanh.getValueAt(row, 1).toString();
            String manv=bangbaohanh.getValueAt(row,3).toString();
            String makh=bangbaohanh.getValueAt(row,2).toString();
            LocalDate ngay=LocalDate.parse(bangbaohanh.getValueAt(row,4).toString());
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".xlsx";
                try {
                    bus.xuatExcel(path,manv,makh,mabh,ngay, (DefaultTableModel) bangbaohanh.getModel());
                } catch (IOException ex) {
                    System.getLogger(BaoHanhDienThoaiUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file Excel thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        }else
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bảo hành để xuất excel");
    }//GEN-LAST:event_btnxuatexcel1ActionPerformed

    private void btnxuatexcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatexcel2ActionPerformed
        // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".xlsx";
                try {
                    bus.xuatExcelTatCa(path, (DefaultTableModel) bangbaohanh.getModel());
                } catch (IOException ex) {
                    System.getLogger(BaoHanhDienThoaiUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file Excel thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
    }//GEN-LAST:event_btnxuatexcel2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row=bangbaohanh.getSelectedRow();
        if(row!=-1){
            String mabh=bangbaohanh.getValueAt(row, 1).toString();
            String manv=bangbaohanh.getValueAt(row,3).toString();
            String makh=bangbaohanh.getValueAt(row,2).toString();
            String ngay=bangbaohanh.getValueAt(row,4).toString();
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".pdf";
                bus.xuatPDF(path,mabh,manv,makh,ngay);
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file PDF thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        }else
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bảo hành để xuất excel");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        thembaohanh.setVisible(true);
        thembaohanh.setSize(500,800);
        String mabh=bus.taoMaBH();
        LocalDate ngay=LocalDate.now();
        String nv= UTIL.TaiKhoanSession.nvDangNhap.getMaNV();
        txtmabaohanh.setText(mabh);
        txtngaylap.setText(ngay.toString());
        txtmanhanvien.setText(nv);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void ok(){
        if (txtmabaohanh.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng không để trống mã bảo hành!");
            return;
        }
        DefaultTableModel model= (DefaultTableModel) bangchitietbaohanh1.getModel();
        for(int i=0;i<model.getRowCount();i++){
            if(model.getValueAt(i,1).equals("")){
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng không để trống mã IMEI!");
                return;
            }
        }
        BaoHanhDTO bh=new BaoHanhDTO();
        String mabh=txtmabaohanh.getText();
        bh.setMaBH(mabh);
        bh.setMaKH(txtmakhachhang.getText());
        bh.setMaNV(txtmanhanvien.getText());
        bh.setNgayLap(LocalDate.parse(txtngaylap.getText()));
        bus.insert(bh);

        ArrayList<ChiTietBaoHanhDTO> ds=new ArrayList<>();
        for(int i=0;i<model.getRowCount();i++){
            ChiTietBaoHanhDTO ctbh=new ChiTietBaoHanhDTO();
            ctbh.setMaBH(mabh);
            ctbh.setIMEI(model.getValueAt(i, 1).toString());
            ctbh.setNgay(LocalDate.parse(model.getValueAt(i, 5).toString()));
            ds.add(ctbh);
        }

        bus.insertCTBH(ds);
        JOptionPane.showMessageDialog(null,"Tạo phiếu bảo hành thành công");
        thembaohanh.setVisible(false);
        int ok=JOptionPane.showConfirmDialog(null, "Bạn có muốn xuất phiếu pdf không");
        if(ok==JOptionPane.YES_OPTION){
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".pdf";
                bus.xuatPDF(path,mabh);
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file PDF thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
    }
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(
            null,
            "Bạn có chắc muốn xóa không?",
            "Xác nhận",
            JOptionPane.YES_NO_OPTION
        );
        if (result == JOptionPane.YES_OPTION) {
            thembaohanh.setVisible(false);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtngaylapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaylapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaylapActionPerformed

    private void txtmahoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahoadonActionPerformed

    private void txtmanhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanhanvienActionPerformed

    private void txttenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenkhActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void bangchitietbaohanh1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bangchitietbaohanh1AncestorAdded
        // TODO add your handling code here:
        int row;
        row=bangchitietbaohanh.getSelectedRow();
        if(row!=-1){
            String imei=  bangchitietbaohanh.getValueAt(row,1).toString();
            txtimei.setText(imei);
        }
    }//GEN-LAST:event_bangchitietbaohanh1AncestorAdded

    private void txtimeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimeiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String imei = txtimei.getText().trim();

        if (imei.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập IMEI");
            return;
        }

        int row = bangchitietbaohanh1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng");
            return;
        }
        boolean kt=true;
        // kiểm tra trùng
        for (int i = 0; i < bangchitietbaohanh1.getRowCount(); i++) {
            if (i == row) continue; // bỏ qua dòng đang chọn

            Object value = bangchitietbaohanh1.getValueAt(i, 1);
            if (value != null && imei.equals(value.toString())) {
                JOptionPane.showMessageDialog(null, "Trùng IMEI");
                return;
            }
        }
        if(kt && !bus.KtIMEI(imei)){
            JOptionPane.showMessageDialog(null, "IMEI này đã được bảo hành");
            return;
        }
        // nếu không trùng thì set
        bangchitietbaohanh1.setValueAt(imei, row, 1);
        txtimei.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtmakhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmakhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmakhachhangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String mahd=txtmahoadon.getText().trim();
        LocalDate ngaylap=LocalDate.parse(txtngaylap.getText());
        if(!bus.kTMaHD(mahd)){
            JOptionPane.showMessageDialog(null,"Không tồn tại mã hóa đơn này");
            return;
        }
        HoaDonDTO hd=bus.getHDByMaHD(mahd);
        KhachHangDTO kh=bus.getKHByMaKH(hd.getMaKH());
        txtmakhachhang.setText(kh.getMa());
        txttenkh.setText(kh.getHoten());
        txtsdt.setText(kh.getDt());
        txtemail.setText(kh.getEmail());
        
        ArrayList<ChiTietHoaDonDTO> ds= bus.geCTHDByMaHD(mahd);
        DefaultTableModel model=(DefaultTableModel) bangchitietbaohanh1.getModel();
        model.setRowCount(0);
        
        int i=1;
        for(ChiTietHoaDonDTO ct:ds){
            int baohanh=bus.getCTSPByMaSP(ct.getMaSP()).getBaoHanh();
            LocalDate han= ngaylap.plusMonths(baohanh);
            Vector row=new Vector();
            for(int j=1;j<=ct.getSoLuong();j++){
                row.add(i++);
                row.add("");
                row.add(ct.getMaSP());
                row.add(ct.getTenSP());
                row.add(baohanh);
                row.add(han);
                model.addRow(row);
            }
            
        }
        bangchitietbaohanh1.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ok();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        baohanh.setVisible(true);
        baohanh.setSize(500,800);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btntimmabaohanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimmabaohanhActionPerformed
        // TODO add your handling code here:
        String mabh=txttimmabaohanh.getText();
        ArrayList<ChiTietBaoHanhDTO> tam=    bus.getCTBHByMaBH(mabh);
        if(tam==null){
            JOptionPane.showMessageDialog(null, "Không tìm thấy mã bảo hành");
            return;
        }
        DefaultTableModel model=(DefaultTableModel) bangchitietbaohanh2.getModel();
        model.setNumRows(0);
        int i=1;
        for(ChiTietBaoHanhDTO ct:tam){
            Vector row= new Vector();
            row.add(i++);
            row.add(ct.getIMEI());
            row.add(ct.getNgay());
            model.addRow(row);
        }
        bangchitietbaohanh2.setModel(model);
        
    }//GEN-LAST:event_btntimmabaohanhActionPerformed
    private void vebanglanbaohanh(ArrayList<LanBaoHanhDTO> tam){
         DefaultTableModel model=(DefaultTableModel) banglanbaohanh.getModel();
            model.setNumRows(0);
            for(LanBaoHanhDTO l:tam){
                Vector rowdata= new Vector();
                rowdata.add(l.getMaLanBH());
                rowdata.add(l.getNgayNhan());
                rowdata.add(l.getNgayTra());
                rowdata.add(l.getTinhTrang());
                rowdata.add(l.getXuLy());
                rowdata.add(l.getTrangThai());
                model.addRow(rowdata);
            }
            banglanbaohanh.setModel(model);
    }
    private void bangchitietbaohanh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangchitietbaohanh2MouseClicked
        // TODO add your handling code here:
        int row=bangchitietbaohanh2.getSelectedRow();
        if(row!=-1){
            String imei=bangchitietbaohanh2.getValueAt(row, 1).toString();
            ArrayList<LanBaoHanhDTO> tam=bus.getDSLBHByIMEI(imei);
            vebanglanbaohanh(tam);
            txttinhtrang.setText("");
            txtxuly.setText("");
        }
    }//GEN-LAST:event_bangchitietbaohanh2MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int row=bangchitietbaohanh2.getSelectedRow();
        String tinhtrang=txttinhtrang.getText();
        if(row!=-1){
            LocalDate ngay= LocalDate.parse(bangchitietbaohanh2.getValueAt(row, 2).toString());
            LocalDate now=LocalDate.now();
            if(now.isAfter(ngay)){
                JOptionPane.showMessageDialog(null, "Hết hạn bảo hành");
                        return;
            }
            for(int i=0;i<banglanbaohanh.getModel().getRowCount();i++)
                if(banglanbaohanh.getValueAt(i, 5).equals("Đang sửa")){
                    JOptionPane.showMessageDialog(null,"Máy đang sửa");
                    return;
                }
            if(tinhtrang.equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tình trạng");
                return;
            }
            String imei=bangchitietbaohanh2.getValueAt(row, 1).toString();
            bus.themLBH(imei, tinhtrang);
            vebanglanbaohanh(bus.getDSLBHByIMEI(imei));
            txttinhtrang.setText("");
            txtxuly.setText("");
        }
        else 
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int row=banglanbaohanh.getSelectedRow();
        int row1=bangchitietbaohanh2.getSelectedRow();
        String tinhtrang=txttinhtrang.getText();
        String xuly=txtxuly.getText();
        if(row!=-1){
            if(tinhtrang.equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tình trạng");
                return;
            }
            if(xuly.equals("")){
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập xử lý");
                return;
            }
            if(!banglanbaohanh.getValueAt(row, 5).toString().equals("Đang sửa")){
                JOptionPane.showMessageDialog(null, "Lần bảo hành này đã hoàn thành vui lòng chọn lần khác");
                return;
            }
            int malbh=Integer.parseInt(banglanbaohanh.getValueAt(row, 0).toString());
            bus.hoanhThanh(malbh, xuly);
            String imei=bangchitietbaohanh2.getValueAt(row1, 1).toString();
            vebanglanbaohanh(bus.getDSLBHByIMEI(imei));
            txttinhtrang.setText("");
            txtxuly.setText("");
            
        }
        else 
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sản phẩm");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void banglanbaohanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banglanbaohanhMouseClicked
        // TODO add your handling code here:
        int row=banglanbaohanh.getSelectedRow();
        if(row!=-1){
            String tinhtrang=banglanbaohanh.getValueAt(row, 3).toString();
            String xuly =banglanbaohanh.getValueAt(row, 4).toString();
            txttinhtrang.setText(tinhtrang);
            txtxuly.setText(xuly);
        }
    }//GEN-LAST:event_banglanbaohanhMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangbaohanh;
    private javax.swing.JTable bangchitietbaohanh;
    private javax.swing.JTable bangchitietbaohanh1;
    private javax.swing.JTable bangchitietbaohanh2;
    private javax.swing.JTable banglanbaohanh;
    private javax.swing.JDialog baohanh;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private javax.swing.JButton btnreset2;
    private javax.swing.JButton btntimmabaohanh;
    private javax.swing.JButton btnxuatexcel1;
    private javax.swing.JButton btnxuatexcel2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cbtimkiem;
    private com.toedter.calendar.JDateChooser datedenngay;
    private com.toedter.calendar.JDateChooser datetungay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog thembaohanh;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtimei;
    private javax.swing.JTextField txtmabaohanh;
    private javax.swing.JTextField txtmahoadon;
    private javax.swing.JTextField txtmakhachhang;
    private javax.swing.JTextField txtmanhanvien;
    private javax.swing.JTextField txtngaylap;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttenkh;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttimmabaohanh;
    private javax.swing.JTextField txttinhtrang;
    private javax.swing.JTextField txtxuly;
    // End of variables declaration//GEN-END:variables
}
