/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import DAO.NhanVienDAO;
import DTO.NhanVienDTO;
import SERVICES.DoiSoLieu;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THANH NHAN
 */
public class NhanVienUI extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienUI
     */
    public NhanVienUI() {
        com.formdev.flatlaf.intellijthemes.FlatNordIJTheme.setup();
        initComponents();
        
        
        loadToData();
        loadCVtoCMB();
    }
    
    static int row = -1 ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        txtMucTieu = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnRemove = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        cmbCV = new javax.swing.JComboBox<>();
        cmbSapXep = new javax.swing.JComboBox<>();
        cmbDT = new javax.swing.JComboBox<>();
        cmbSXtheo = new javax.swing.JComboBox<>();
        btnApply = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(69, 66, 158));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1700, 60));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 39)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN CỬA HÀNG BÁN ĐIỆN THOẠI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(756, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(820, 90));

        txtMucTieu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMucTieuKeyTyped(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtMucTieu, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnReset)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMucTieu))
                .addContainerGap())
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        jToolBar1.setRollover(true);

        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bin.png"))); // NOI18N
        btnRemove.setText(" Xóa ");
        btnRemove.setFocusable(false);
        btnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRemove);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pen.png"))); // NOI18N
        btnEdit.setText("   Sửa   ");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnDetail.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/document.png"))); // NOI18N
        btnDetail.setText("Xem chi tiết");
        btnDetail.setFocusable(false);
        btnDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDetail);
        jToolBar1.add(jSeparator1);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel.png"))); // NOI18N
        jButton5.setText("Nhập Excel");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel (2).png"))); // NOI18N
        jButton6.setText("Xuất Excel");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Nhân Viên", "Họ và Tên", "Email", "Giới Tính", "Ngày Sinh", "Chức Vụ", "Lương", "Trạng Thái"
            }
        ));
        tblNhanVien.setRowHeight(30);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        tblNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblNhanVienKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(40);
            tblNhanVien.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblNhanVien.getColumnModel().getColumn(1).setMaxWidth(120);
            tblNhanVien.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblNhanVien.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblNhanVien.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblNhanVien.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblNhanVien.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        cmbCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","Giảm dần", "Tăng dần" }));

        cmbDT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn độ tuổi","18-25", "26 -30", "31-45", "46-60" }));

        cmbSXtheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn kiểu","Mã Nhân Viên", "Họ Tên", "Ngày Sinh", "Lương" }));

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnCancle.setText("Cancel");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDT, 0, 148, Short.MAX_VALUE)
                            .addComponent(cmbCV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSXtheo, 0, 145, Short.MAX_VALUE)
                            .addComponent(cmbSapXep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnApply, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnCancle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSXtheo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApply))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancle))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadToData(){
        try{
            int i = 1;
            NhanVienDAO nvDAO = new NhanVienDAO();
            
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            
            model.setRowCount(0);
            
            for(NhanVienDTO nv : nvDAO.selectAll()){
                Vector<Object> row = new Vector<>();
                row.add(i++);
                row.add(nv.getMaNV());
                row.add(nv.getHoTenNV());
                row.add(nv.getEmailNV());
                row.add(nv.getGioiTinhNV());
                row.add(nv.getNgaySinhNV());
                row.add(nv.getChucVuNV());
                String nvLuong = DoiSoLieu.doiTien(nv.getLuongNV());
                row.add(nvLuong);
                row.add(nv.isTinhTrangNV());
               
                model.addRow(row);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void loadToTable (ArrayList<NhanVienDTO> ds){
        try{
            int i = 1;
            NhanVienBUS nvBUS = new NhanVienBUS();
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            
            model.setRowCount(0);
            
            for(NhanVienDTO nv : ds){
                Vector<Object> row = new Vector<>();
                row.add(i++);
                row.add(nv.getMaNV());
                row.add(nv.getHoTenNV());
                row.add(nv.getEmailNV());
                row.add(nv.getGioiTinhNV());
                row.add(nv.getNgaySinhNV());
                row.add(nv.getChucVuNV());
                String nvLuong = DoiSoLieu.doiTien(nv.getLuongNV());
                row.add(nvLuong);
                row.add(nv.isTinhTrangNV());
               
                model.addRow(row);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }  
    }
    public void loadCVtoCMB(){
        cmbCV.removeAllItems();
        cmbCV.addItem("Chọn chức vụ");
        
        NhanVienBUS nvBUS = new NhanVienBUS();
        if(nvBUS.getDSNV() == null ){
            nvBUS.docDSNV();
        }
        
        ArrayList<String> dscv = new ArrayList<>();
        
        for(NhanVienDTO nv : nvBUS.getDSNV()){
            String chucvu = nv.getChucVuNV();
            if(chucvu != null  || chucvu.trim().isEmpty()){
                if(!dscv.contains(chucvu)){
                    dscv.add(chucvu);
                    cmbCV.addItem(chucvu);
                }
            }
        }
    }
    
    //
    
    // logic cho các nút chức năng

    
// nut reset
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMucTieu.setText("");
        loadToData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        row = tblNhanVien.getSelectedRow();
        
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void tblNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblNhanVienKeyReleased
        // TODO add your handling code here:
        row = tblNhanVien.getSelectedRow();
    }//GEN-LAST:event_tblNhanVienKeyReleased


// nut xoa thong tin nhan vien
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        row = tblNhanVien.getSelectedRow();
        String ma = tblNhanVien.getValueAt(row, 1).toString();// row la hang 1 la cot 
        
        NhanVienDTO nvDTO = new NhanVienDTO();// gan lai cai ma cho dto 
        nvDTO.setMaNV(ma);
        
        NhanVienBUS nvBUS = new NhanVienBUS();// chuyen no xuong cho thanh bus =  chuyen sang dao
        nvBUS.xoa(nvDTO);
        
        loadToData();
    }//GEN-LAST:event_btnRemoveActionPerformed


// nut sua thong tin nhan vien
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        row = tblNhanVien.getSelectedRow();
        if(row == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Vui long chon dong muon sua");
            return ;
        }
        // hien thi giao dien sua nhan vien 
        SuaNhanVienUI suaForm = new SuaNhanVienUI();

        // hien thi thong tin len bang suanhanvien
        
        try{
            String ma = tblNhanVien.getValueAt(row, 1).toString();
            String hoten = tblNhanVien.getValueAt(row, 2).toString();
            String email = tblNhanVien.getValueAt(row, 3).toString();
            String gt = tblNhanVien.getValueAt(row, 4).toString();
            java.util.Date ns = (java.util.Date) tblNhanVien.getValueAt(row, 5);
            String cv = tblNhanVien.getValueAt(row, 6).toString();
            String l = tblNhanVien.getValueAt(row, 7).toString();
            String tt = tblNhanVien.getValueAt(row, 8).toString();
          
            
            suaForm.setThongTin(ma, hoten, email, gt, ns , cv, l ,tt);
            
            
            suaForm.setModal(true);
            suaForm.setLocationRelativeTo(null);
            suaForm.setVisible(true);
            
            loadToData();
        
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"loi trich xuat du lieu");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnEditActionPerformed



// nut xem thong tin chi tiet
    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        row = tblNhanVien.getSelectedRow();
        if(row == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Vui long chon dong muon sua");
            return ;
        }
        // hien thi giao dien sua nhan vien 
        XemTTNhanVienUI thongtinForm = new XemTTNhanVienUI();

        
        
        // hien thi thong tin len bang suanhanvien
        
        try{
            String ma = tblNhanVien.getValueAt(row, 1).toString();
            String hoten = tblNhanVien.getValueAt(row, 2).toString();
            String email = tblNhanVien.getValueAt(row, 3).toString();
            String gt = tblNhanVien.getValueAt(row, 4).toString();
            java.util.Date ns = (java.util.Date) tblNhanVien.getValueAt(row, 5);
            String cv = tblNhanVien.getValueAt(row, 6).toString();
            String l = tblNhanVien.getValueAt(row, 7).toString();
            String tt = tblNhanVien.getValueAt(row, 8).toString();
            
            thongtinForm.setThongTin(ma, hoten, email,gt , ns , cv, l , tt);
            
            
            
            thongtinForm.setLocationRelativeTo(null);
            thongtinForm.setVisible(true);
            
            loadToData();
        
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"Lỗi trích xuất dữ liệu");
            e.printStackTrace();
        }
        
    
    }//GEN-LAST:event_btnDetailActionPerformed


// nut trong thanh tim kiem
    private void txtMucTieuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMucTieuKeyTyped
        // TODO add your handling code here:
        String muctieu = txtMucTieu.getText();
        
        NhanVienBUS nvBUS = new NhanVienBUS();
        ArrayList<NhanVienDTO> dstk = nvBUS.timkiem(muctieu);
        
        loadToTable(dstk);
    }//GEN-LAST:event_txtMucTieuKeyTyped


    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        String mucTieu = txtMucTieu.getText();
        String chucVu = cmbCV.getSelectedItem().toString();
        String doTuoi = cmbDT.getSelectedItem().toString();
        String kieu = cmbSXtheo.getSelectedItem().toString();
        String sapXep = cmbSapXep.getSelectedItem().toString();
        
        
        NhanVienBUS nvBUS = new NhanVienBUS();
        ArrayList<NhanVienDTO> dstknc = nvBUS.timKiemNangCao (mucTieu ,chucVu, doTuoi, kieu, sapXep);

        loadToTable(dstknc);
    }//GEN-LAST:event_btnApplyActionPerformed
            
    private int docVaLuuNhanVien(java.io.File fileOpen) throws Exception {
        int count = 0;
        java.io.FileInputStream fis = new java.io.FileInputStream(fileOpen);
        org.apache.poi.xssf.usermodel.XSSFWorkbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook(fis);
        org.apache.poi.xssf.usermodel.XSSFSheet sheet = workbook.getSheetAt(0);

        DAO.NhanVienDAO nvDAO = new DAO.NhanVienDAO();

        for (int i = 1; i <= sheet.getLastRowNum(); i++) {
            org.apache.poi.xssf.usermodel.XSSFRow row = sheet.getRow(i);
            if (row != null) {
                DTO.NhanVienDTO nv = new DTO.NhanVienDTO();

               
                String maNV = "";
                if (row.getCell(1) != null) {
                    maNV = row.getCell(1).getStringCellValue().trim();
                }

               
                
                if (maNV.isEmpty()) {
                    continue;
                }

                // Nếu có mã đàng hoàng thì mới set vào đối tượng và đi tiếp
                nv.setMaNV(maNV);
                // ----------------
                if (row.getCell(2) != null) {
                    nv.setHoTenNV(row.getCell(2).getStringCellValue());
                }
                if (row.getCell(3) != null) {
                    nv.setEmailNV(row.getCell(3).getStringCellValue());
                }
                if (row.getCell(4) != null) {
                    nv.setGioiTinhNV(row.getCell(4).getStringCellValue());
                }

                if (row.getCell(5) != null) {
                    try {
                        java.util.Date utilDate = row.getCell(5).getDateCellValue();
                        // Bổ sung kiểm tra khác null trước khi gọi getTime()
                        if (utilDate != null) {
                            nv.setNgaySinhNV(new java.sql.Date(utilDate.getTime()));
                        }
                    } catch (Exception e) {
                        // Bỏ qua lỗi nếu lỡ tay gõ chữ vào cột ngày sinh
                        System.out.println("Cảnh báo: Sai định dạng ngày ở dòng " + i);
                    }
                }
                if (row.getCell(6) != null) {
                    nv.setChucVuNV(row.getCell(6).getStringCellValue());
                }

                org.apache.poi.ss.usermodel.DataFormatter formatter = new org.apache.poi.ss.usermodel.DataFormatter();


                if (row.getCell(7) != null) {
                    // 1. DataFormatter sẽ tự động đọc mọi thứ trong ô (Số, Chữ, Công thức) và biến thành Chuỗi chuẩn
                    String tienLuong = formatter.formatCellValue(row.getCell(7)).trim();

                    // 2. Dọn dẹp dữ liệu: Xóa các dấu phẩy, dấu chấm nếu Excel tự động định dạng tiền tệ (VD: 10,000,000 -> 10000000)
                    tienLuong = tienLuong.replace(",", "").replace(".", "");

                    // 3. Kiểm tra và gán vào DTO
                    if (tienLuong.isEmpty()) {
                        nv.setLuongNV("0"); // Chỉ khi nào ô thực sự không có gì mới gán bằng 0
                    } else {
                        nv.setLuongNV(tienLuong); // Nạp con số thuần túy vào hệ thống
                    }
                } else {
                    nv.setLuongNV("0");
                }
                if (row.getCell(8) != null) {
                    String tt = row.getCell(8).toString().trim();
                    nv.setTinhTrangNV(tt.equalsIgnoreCase("true") || tt.equals("1") || tt.equals("1.0"));
                }

                if (nvDAO.themTuExcel(nv) > 0) {
                    count++;
                }
            }
        }
        workbook.close();
        fis.close();
        return count;
    }
    private int docVaLuuTaiKhoan(java.io.File fileOpen) throws Exception {
    int count = 0;
    java.io.FileInputStream fis = new java.io.FileInputStream(fileOpen);
    org.apache.poi.xssf.usermodel.XSSFWorkbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook(fis);
    org.apache.poi.xssf.usermodel.XSSFSheet sheet = workbook.getSheetAt(0); 

    // Gọi đến lớp DAO quản lý Tài Khoản
    DAO.TaiKhoanNVDAO tkDAO = new DAO.TaiKhoanNVDAO(); 

    for (int i = 1; i <= sheet.getLastRowNum(); i++) {
        org.apache.poi.xssf.usermodel.XSSFRow row = sheet.getRow(i);
        if (row != null) {
            DTO.TaiKhoanNVDTO tk = new DTO.TaiKhoanNVDTO();
            
            // Lấy Mã, Tài khoản, Mật khẩu
            if (row.getCell(1) != null) tk.setMaNV(row.getCell(1).getStringCellValue());
            if (row.getCell(2) != null) tk.setTaiKhoan(row.getCell(2).getStringCellValue());
            
            if (row.getCell(3) != null) {
                if (row.getCell(3).getCellType() == org.apache.poi.ss.usermodel.CellType.NUMERIC) {
                    tk.setMatKhau(String.valueOf((long) row.getCell(3).getNumericCellValue()));
                } else {
                    tk.setMatKhau(row.getCell(3).getStringCellValue());
                }
            }

            // Lưu xuống Database
            if (tkDAO.themTuExcel(tk) > 0) {
                count++;
            }
        }
    }
    workbook.close();
    fis.close();
    return count;
}
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Mở hộp thoại chọn file Nhân Viên
            javax.swing.JFileChooser fcNV = new javax.swing.JFileChooser();
            fcNV.setDialogTitle("Bước 1: Chọn file Excel NHÂN VIÊN");
            int chonNV = fcNV.showOpenDialog(this);

            if (chonNV != javax.swing.JFileChooser.APPROVE_OPTION) {
                return; // Dừng lại nếu người dùng tắt bảng chọn file
            }
            java.io.File fileNV = fcNV.getSelectedFile();

            // 2. Hiện thông báo xác nhận bước tiếp theo
            int xacNhan = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Đã chọn xong file Nhân Viên.\nBạn có muốn mở tiếp thư mục để chọn file Tài Khoản không.\n(Nếu chọn No/Cancel, lệnh nhập Nhân Viên sẽ bị hủy bỏ hoàn toàn)",
                    "Yêu cầu xác nhận",
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (xacNhan != javax.swing.JOptionPane.YES_OPTION) {
                javax.swing.JOptionPane.showMessageDialog(this, "Đã hủy quá trình nhập dữ liệu.");
                return; // Dừng lại tại đây, chưa có lệnh SQL nào được chạy
            }

            // 3. Mở hộp thoại chọn file Tài Khoản
            javax.swing.JFileChooser fcTK = new javax.swing.JFileChooser();
            fcTK.setDialogTitle("Bước 2: Chọn file Excel TÀI KHOẢN");
            int chonTK = fcTK.showOpenDialog(this);

            if (chonTK != javax.swing.JFileChooser.APPROVE_OPTION) {
                javax.swing.JOptionPane.showMessageDialog(this, "Hủy tiến trình vì chưa chọn file Tài Khoản.");
                return;
            }
            java.io.File fileTK = fcTK.getSelectedFile();

            // 4. Bắt đầu đọc file và lưu vào Database theo đúng thứ tự (Cha trước, Con sau)
            int soNhanVien = docVaLuuNhanVien(fileNV);
            int soTaiKhoan = docVaLuuTaiKhoan(fileTK);

            javax.swing.JOptionPane.showMessageDialog(this, "Hoàn tất.\n- Đã thêm: " + soNhanVien + " nhân viên.\n- Đã thêm: " + soTaiKhoan + " tài khoản.");

            // 5. Load lại bảng giao diện
            // loadDataToTable(nvBUS.getDS()); // Mở ghi chú dòng này theo tên hàm của em
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi chạy tiến trình: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Mở hộp thoại cho người dùng chọn nơi lưu file
            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi lưu file Excel");
            int userSelection = fileChooser.showSaveDialog(this);

            if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File fileToSave = fileChooser.getSelectedFile();
                // Đảm bảo đuôi file là .xlsx
                String filePath = fileToSave.getAbsolutePath();
                if (!filePath.endsWith(".xlsx")) {
                    filePath += ".xlsx";
                }

                // 2. Tạo một file Excel mới trong bộ nhớ
                org.apache.poi.xssf.usermodel.XSSFWorkbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
                org.apache.poi.xssf.usermodel.XSSFSheet sheet = workbook.createSheet("DanhSachNhanVien");

                // 3. Tạo dòng Tiêu đề (Header) từ cột của JTable
                org.apache.poi.xssf.usermodel.XSSFRow headerRow = sheet.createRow(0);
                for (int i = 0; i < tblNhanVien.getColumnCount(); i++) {
                    org.apache.poi.xssf.usermodel.XSSFCell cell = headerRow.createCell(i);
                    cell.setCellValue(tblNhanVien.getColumnName(i));
                }

                // 4. Lấy dữ liệu từ JTable đổ vào các dòng Excel
                for (int i = 0; i < tblNhanVien.getRowCount(); i++) {
                    org.apache.poi.xssf.usermodel.XSSFRow row = sheet.createRow(i + 1);
                    for (int j = 0; j < tblNhanVien.getColumnCount(); j++) {
                        org.apache.poi.xssf.usermodel.XSSFCell cell = row.createCell(j);
                        Object value = tblNhanVien.getValueAt(i, j);
                        if (value != null) {
                            cell.setCellValue(value.toString());
                        }
                    }
                }

                // 5. Ghi ra ổ cứng và đóng luồng
                java.io.FileOutputStream out = new java.io.FileOutputStream(filePath);
                workbook.write(out);
                out.close();
                workbook.close();

                javax.swing.JOptionPane.showMessageDialog(this, "Xuất Excel thành công!\nĐã lưu tại: " + filePath);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi xuất file: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        // TODO add your handling code here:
        cmbCV.setSelectedIndex(0);
        cmbDT.setSelectedIndex(0);
        cmbSXtheo.setSelectedIndex(0);
        cmbSapXep.setSelectedIndex(0);
        
        loadToData();
        
    }//GEN-LAST:event_btnCancleActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbCV;
    private javax.swing.JComboBox<String> cmbDT;
    private javax.swing.JComboBox<String> cmbSXtheo;
    private javax.swing.JComboBox<String> cmbSapXep;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtMucTieu;
    // End of variables declaration//GEN-END:variables
}
