/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import static GUI.NhanVienUI.row;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author THANH NHAN
 */
public class SuaNhanVienUI extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SuaNhanVienUI.class.getName());

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form ThemNCCUI
     */
    public SuaNhanVienUI() {
        com.formdev.flatlaf.intellijthemes.FlatSolarizedLightIJTheme.setup();
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSuaMaNV = new javax.swing.JTextField();
        txtSuaEmailNV = new javax.swing.JTextField();
        txtSuaTenNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbnTrue = new javax.swing.JRadioButton();
        rbnFalse = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cmbChucVuNV = new javax.swing.JComboBox<>();
        dcNgaySinhNV = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        lbluong = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        cmbGioiTinh = new javax.swing.JComboBox<>();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(0, 102, 102));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(151, 180, 198));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sửa TT Nhân Viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Mã Nhân Viên");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Tên Nhân Viên");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("Ngày Sinh");

        txtSuaMaNV.setBackground(new java.awt.Color(230, 230, 230));
        txtSuaMaNV.setForeground(new java.awt.Color(0, 0, 0));
        txtSuaMaNV.setText("\n");

        txtSuaEmailNV.setBackground(new java.awt.Color(230, 230, 230));
        txtSuaEmailNV.setForeground(new java.awt.Color(0, 0, 0));
        txtSuaEmailNV.setText("\n");

        txtSuaTenNV.setBackground(new java.awt.Color(230, 230, 230));
        txtSuaTenNV.setForeground(new java.awt.Color(0, 0, 0));
        txtSuaTenNV.setText("\n");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText("Chức Vụ");

        buttonGroup1.add(rbnTrue);
        rbnTrue.setText("True");
        rbnTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnTrueActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnFalse);
        rbnFalse.setText("False");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Tình Trạng");

        cmbChucVuNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Lý" ,"Kho" , "Bán hàng" , "Bảo vệ" ,"Kỹ thuật" , "Thực tập" , "Kế toán"}));
        cmbChucVuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucVuNVActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setText("Giới Tính");

        lbluong.setBackground(new java.awt.Color(0, 0, 0));
        lbluong.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbluong.setText("Lương");

        txtLuong.setBackground(new java.awt.Color(230, 230, 230));
        txtLuong.setForeground(new java.awt.Color(0, 0, 0));
        txtLuong.setText("\n");

        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dcNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rbnTrue)
                                .addGap(65, 65, 65)
                                .addComponent(rbnFalse))
                            .addComponent(cmbChucVuNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(116, 116, 116))))
                    .addComponent(txtSuaTenNV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSuaMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSuaEmailNV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(cmbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbluong)
                            .addComponent(txtLuong))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSuaMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtSuaTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtSuaEmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbluong))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(cmbGioiTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbChucVuNV)
                    .addComponent(dcNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbnTrue)
                    .addComponent(rbnFalse))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getRootPane().setDefaultButton(btnSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void quyenAmdin(boolean chophep){
        cmbChucVuNV.setEnabled(chophep);
        rbnFalse.setEnabled(chophep);
        rbnTrue.setEnabled(chophep);
        txtLuong.setEnabled(chophep);
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

       String ma = txtSuaMaNV.getText();
        String ten = txtSuaTenNV.getText();
        String email = txtSuaEmailNV.getText();
        String gioitinh = cmbGioiTinh.getSelectedItem().toString();
        java.util.Date ngaySinh = dcNgaySinhNV.getDate();
        String chucVu = cmbChucVuNV.getSelectedItem().toString();
        
       
        String luong = txtLuong.getText().trim();
        
       
        if (luong.endsWith(".0")) {
            luong = luong.substring(0, luong.length() - 2); 
        }
        
        
        luong = luong.replace(",", "").replace(".", "");
        
        // Bước 3: Bắt đầu kiểm tra logic
        if (luong.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Tiền lương không được để trống!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        if (!luong.matches("^[1-9][0-9]*$")) {
            JOptionPane.showMessageDialog(this, "Lương không hợp lệ! Vui lòng chỉ nhập số nguyên và không bắt đầu bằng số 0.", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        boolean tinhTrang = true;
        if(rbnTrue.isSelected()){
            tinhTrang = true;
        }else{
            rbnFalse.isSelected();
            tinhTrang = false;
        }

        NhanVienDTO nvDTO = new NhanVienDTO();
        nvDTO.setMaNV(ma);
        nvDTO.setHoTenNV(ten);
        nvDTO.setEmailNV(email);
        nvDTO.setGioiTinhNV(gioitinh);
        
        if (ngaySinh != null) {
            java.sql.Date sqlNgaySinh = new java.sql.Date(ngaySinh.getTime());
            nvDTO.setNgaySinhNV(sqlNgaySinh);
        }
        
        nvDTO.setChucVuNV(chucVu);
        nvDTO.setLuongNV(luong);
        nvDTO.setTinhTrangNV(tinhTrang);
        
        
        NhanVienBUS nvBUS = new NhanVienBUS();
        String thongbao = nvBUS.kiemTraHopLe(nvDTO);
        
        if(!thongbao.equals("OK")){
            JOptionPane.showMessageDialog(this, thongbao, "Lỗi kiểm tra", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
       
        boolean ketQuaLuu = nvBUS.sua(nvDTO);

        if (ketQuaLuu == true) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lưu thông tin thành công!");
            doClose(RET_OK); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lưu thất bại! Hãy kiểm tra lại thông tin.", "Lỗi Dữ Liệu", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancelActionPerformed

    public void setThongTin(String ma, String hoten, String email, String gt, java.util.Date ns, String cv, String l, String tt) {// muc dich tao mot cong de tiep nhan thong tin tu hamsuathongtin
        txtSuaMaNV.setText(ma);
        txtSuaTenNV.setText(hoten);
        txtSuaEmailNV.setText(email);
        
        dcNgaySinhNV.setDate(ns);
       
        txtLuong.setText(l);
        
        for (int i = 0; i < cmbChucVuNV.getItemCount(); i++) {
          
            if (cmbChucVuNV.getItemAt(i).toString().trim().equalsIgnoreCase(cv.trim())) {
                cmbChucVuNV.setSelectedIndex(i);
                break;
            }
        }

        for (int i = 0; i < cmbGioiTinh.getItemCount(); i++) {
            if (cmbGioiTinh.getItemAt(i).toString().trim().equalsIgnoreCase(gt.trim())) {
                cmbGioiTinh.setSelectedIndex(i);
                break;
            }
        }
        
        
        if (tt.trim().equalsIgnoreCase("true") || tt.trim().equals("1")) {
            rbnTrue.setSelected(true);
            rbnFalse.setSelected(false); // Tắt nút False đi
        } else {
            rbnTrue.setSelected(false);
            rbnFalse.setSelected(true);  // Bật nút False lên (Rất quan trọng!)
        }

        txtSuaMaNV.setEditable(false);
        txtSuaMaNV.setBackground(Color.GRAY);
    }

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void rbnTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnTrueActionPerformed

    private void cmbChucVuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucVuNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChucVuNVActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SuaNhanVienUI dialog = new SuaNhanVienUI();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbChucVuNV;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private com.toedter.calendar.JDateChooser dcNgaySinhNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbluong;
    private javax.swing.JRadioButton rbnFalse;
    private javax.swing.JRadioButton rbnTrue;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtSuaEmailNV;
    private javax.swing.JTextField txtSuaMaNV;
    private javax.swing.JTextField txtSuaTenNV;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
