/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.HoaDonBUS;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author THANH NHAN
 */
public class THHoaDonUI extends javax.swing.JPanel {
    HoaDonBUS bus=new HoaDonBUS();
    /**
     * Creates new form PhieuNhapUI
     */
    public THHoaDonUI() {
        com.formdev.flatlaf.intellijthemes.FlatNordIJTheme.setup();
        
        initComponents();
        customTable();
        veBangTHHoaDon();
        veCbMaNV();
    }

    public void veBangTHHoaDon(){
        ArrayList<HoaDonDTO> ds=bus.selectAll();
        Vector header =new Vector();
        header.add("Mã hóa đơn");
        header.add("Nhân viên");
        header.add("Ngày lập");
        header.add("Khách hàng");
        header.add("Tổng tiền");
        header.add("Phương thức thanh toán");
        DefaultTableModel model=new DefaultTableModel(header,0);
        for(HoaDonDTO hd:ds){
            Vector row=new Vector();
            row.add(hd.getMaHD());
            row.add(hd.getMaNV());
            //NhanVienDTO nv= bus.getNVByMaNV(hd.getMaNV());
            //row.add(nv.getHoTenNV());
            row.add(hd.getNgay());
            //KhachHangDTO kh=bus.getKHByMaKH(hd.getMaKH());
            //row.add(kh.getHoten());
            row.add(hd.getMaKH());
            row.add(hd.getTongTien());
            row.add(hd.getPTTT());
            model.addRow(row);
        }
        banghoadon.setModel(model);
    }
        public void veBangTHHoaDonTimKiem(ArrayList<HoaDonDTO> ds){
        Vector header =new Vector();
        header.add("Mã hóa đơn");
        header.add("Nhân viên");
        header.add("Ngày lập");
        header.add("Khách hàng");
        header.add("Tổng tiền");
        header.add("Phương thức thanh toán");
        DefaultTableModel model=new DefaultTableModel(header,0);
        for(HoaDonDTO hd:ds){
            Vector row=new Vector();
            row.add(hd.getMaHD());
            row.add(hd.getMaNV());
            //NhanVienDTO nv= bus.getNVByMaNV(hd.getMaNV());
            //row.add(nv.getHotenNV());
            row.add(hd.getNgay());
            //KhachHangDTO kh=bus.getKHByMaKH(hd.getMaKH());
            //row.add(kh.getHoten());
            row.add(hd.getMaKH());
            row.add(hd.getTongTien());
            row.add(hd.getPTTT());
            model.addRow(row);
        }
        banghoadon.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void customTable() {
        
        java.awt.Font tableFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18);
        banghoadon.setFont(tableFont);
        banghoadon.setRowHeight(30);

        banghoadon.getTableHeader().setOpaque(false);
        banghoadon.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));

        
        bangchitiethoadon.setFont(tableFont);
        bangchitiethoadon.setRowHeight(30);

        bangchitiethoadon.getTableHeader().setOpaque(false);
        bangchitiethoadon.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < banghoadon.getColumnCount(); i++) {
            banghoadon.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        for (int i = 0; i < bangchitiethoadon.getColumnCount(); i++) {
            bangchitiethoadon.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    private void resizeColumnWidth(javax.swing.JTable table) {
        final javax.swing.table.TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 70; 
            for (int row = 0; row < table.getRowCount(); row++) {
                javax.swing.table.TableCellRenderer renderer = table.getCellRenderer(row, column);
                java.awt.Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 15, width);
            }
            if (width > 400) {
                width = 400; 
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
    public void reset(){
                txttimkiemhoadon.setText("");
        cbpttt.setSelectedIndex(0);
        cbmanv.setSelectedIndex(0);
        datetungay.setDate(null);
        datedenngay.setDate(null);
        giatu.setValue(0);
        giaden.setValue(0);
        veBangTHHoaDon();
    }
    public void timKiem(){
        String key=txttimkiemhoadon.getText();
        String pttt=null;
        if(cbpttt.getSelectedIndex()!=0) pttt=cbpttt.getSelectedItem().toString();
        String manv=null;
        if(cbmanv.getSelectedIndex()!=0) manv=cbmanv.getSelectedItem().toString();
        LocalDate tungay=null;
        if(datetungay.getDate()!=null) tungay=datetungay.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate denngay=null;
        if(datedenngay.getDate()!=null) denngay=datedenngay.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int tu=0,den=Integer.MAX_VALUE;
        if(ckgia.isSelected()){
            tu=Integer.parseInt(giatu.getValue().toString());
            den=Integer.parseInt(giaden.getValue().toString());
            if(tu>den){
                JOptionPane.showMessageDialog(null, "Giá từ không được lớn hơn giá đến");
                return;
            }
        }
        ArrayList<HoaDonDTO> tam=bus.timKiem(key,pttt,manv,tungay,denngay,tu,den);
        veBangTHHoaDonTimKiem(tam);
    }
    
    public void veBangChiTietHoaDon(ArrayList<ChiTietHoaDonDTO> ds){
        Vector header =new Vector();
        header.add("Mã sản phẩm");
        header.add("Tên sản phẩm");
        header.add("Số lượng");
        header.add("Đơn giá");
        header.add("Thành tiền");
        DefaultTableModel model=new DefaultTableModel(header,0);
        for(ChiTietHoaDonDTO tk:ds){
            Vector row=new Vector();
            row.add(tk.getMaSP());
            row.add(tk.getTenSP());
            row.add(tk.getSoLuong());
            row.add(tk.getDonGia());
            row.add(tk.getThanhTien());
            model.addRow(row);
        }
        bangchitiethoadon.setModel(model);
    }
    public void hienChiTiet(){
        int row=banghoadon.getSelectedRow();
        if(row!=-1){
            ArrayList<ChiTietHoaDonDTO> ds= bus.getCTHDByMaHD(banghoadon.getValueAt(row,0).toString());
            veBangChiTietHoaDon(ds);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnxuatexcel = new javax.swing.JButton();
        btnxuatexcel1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbpttt = new javax.swing.JComboBox<>();
        txttimkiemhoadon = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datetungay = new com.toedter.calendar.JDateChooser();
        datedenngay = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        giatu = new javax.swing.JSpinner();
        giaden = new javax.swing.JSpinner();
        ckgia = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        cbmanv = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        banghoadon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangchitiethoadon = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1710, 305));

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(505, 100));
        jToolBar1.add(jSeparator1);

        btnxuatexcel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnxuatexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel (2).png"))); // NOI18N
        btnxuatexcel.setText("Xuất Excel");
        btnxuatexcel.setFocusable(false);
        btnxuatexcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuatexcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuatexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatexcelActionPerformed(evt);
            }
        });
        jToolBar1.add(btnxuatexcel);

        btnxuatexcel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnxuatexcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/excel (2).png"))); // NOI18N
        btnxuatexcel1.setText("Xuất Excel Tất cả");
        btnxuatexcel1.setFocusable(false);
        btnxuatexcel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnxuatexcel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnxuatexcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatexcel1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnxuatexcel1);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pdf.png"))); // NOI18N
        jButton4.setText("Xuất PDF");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(820, 90));

        cbpttt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn phương thức thanh toán", "Chuyển khoản", "Tiền mặt" }));
        cbpttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbptttActionPerformed(evt);
            }
        });

        txttimkiemhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemhoadonActionPerformed(evt);
            }
        });

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnreset.setText("Làm mới");
        btnreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbpttt, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttimkiemhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(250, 250, 250))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbpttt)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimkiemhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc theo ngày", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 16))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(601, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Từ:");

        datetungay.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datetungayAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        datedenngay.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datedenngayAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Đến:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datetungay, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(datedenngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datetungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datedenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc theo giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 16))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Từ:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Đến:");

        ckgia.setText("Lọc giá");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(26, 26, 26)
                            .addComponent(giatu, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(giaden)))
                    .addComponent(ckgia))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckgia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(giatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(giaden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc theo Mã nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 16))); // NOI18N

        cbmanv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn mã nhân viên" }));
        cbmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmanvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbmanv, 0, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(18, 77, 122));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 41)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TỔNG HỢP HÓA ĐƠN MUA HÀNG");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(1083, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        banghoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Người tạo hóa đơn", "Tổng tiền", "Mã nhân viên tạo"
            }
        ));
        banghoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hienchitiet(evt);
            }
        });
        jScrollPane1.setViewportView(banghoadon);

        bangchitiethoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(bangchitiethoadon);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnresetActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void veCbMaNV(){
        ArrayList<NhanVienDTO> ds=bus.getDSNV();
        Vector row=new Vector();
        row.add("Chọn nhân viên");
        for(NhanVienDTO nv:ds)
            row.add(nv.getMaNV()+"-"+nv.getHoTenNV());
        DefaultComboBoxModel model= new DefaultComboBoxModel(row);
        cbmanv.setModel(model);
    }
    
    private void txttimkiemhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemhoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemhoadonActionPerformed

    private void cbmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmanvActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbmanvActionPerformed

    private void btnxuatexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatexcelActionPerformed
        // TODO add your handling code here:
        int row=banghoadon.getSelectedRow();
        if(row!=-1){
            String mahd=banghoadon.getValueAt(row, 0).toString();
            String manv=banghoadon.getValueAt(row,1).toString();
            String makh=banghoadon.getValueAt(row,3).toString();
            String ngay=banghoadon.getValueAt(row,2).toString();
            String tongtien=banghoadon.getValueAt(row,4).toString();
            String pttt=banghoadon.getValueAt(row,5).toString();
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".xlsx";
                try {
                    bus.xuatExcel(path,manv,makh,mahd,ngay,pttt,tongtien,(DefaultTableModel) bangchitiethoadon.getModel());
                } catch (IOException ex) {
                    System.getLogger(BaoHanhDienThoaiUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file Excel thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        }else
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bảo hành để xuất excel");
        
    }//GEN-LAST:event_btnxuatexcelActionPerformed

    private void cbptttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbptttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbptttActionPerformed

    private void hienchitiet(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hienchitiet
        // TODO add your handling code here:
        hienChiTiet();
    }//GEN-LAST:event_hienchitiet

    private void btnxuatexcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatexcel1ActionPerformed
        // TODO add your handling code here:
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".xlsx";
                try {
                    bus.xuatExcelTatCa(path,(DefaultTableModel) banghoadon.getModel());
                } catch (IOException ex) {
                    System.getLogger(BaoHanhDienThoaiUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file Excel thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
    }//GEN-LAST:event_btnxuatexcel1ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row=banghoadon.getSelectedRow();
        if(row!=-1){
            String mahd=banghoadon.getValueAt(row, 0).toString();
            String manv=banghoadon.getValueAt(row,1).toString();
            String makh=banghoadon.getValueAt(row,3).toString();
            String ngay=banghoadon.getValueAt(row,2).toString();
            String tongtien=banghoadon.getValueAt(row,4).toString();
            String pttt=banghoadon.getValueAt(row,5).toString();
            JFileChooser fileChooser = new JFileChooser();
            int kq = fileChooser.showSaveDialog(null);
            if(kq==JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                String path = file.getAbsolutePath() + ".pdf";
                bus.xuatPDF(path,mahd,manv,makh,ngay,tongtien,pttt);
                JOptionPane.showMessageDialog(
                    null,
                    "Xuất file PDF thành công!",
                    "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        }else
        JOptionPane.showMessageDialog(null, "Vui lòng chọn bảo hành để xuất excel");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void datetungayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datetungayAncestorAdded
        // TODO add your handling code here:
        Date tu = datetungay.getDate();
        Date den = datedenngay.getDate();

        if (tu != null && den != null && tu.after(den)) {
            JOptionPane.showMessageDialog(null, "Ngày đến phải >= ngày từ!");
            datetungay.setDate(null);
        }
    }//GEN-LAST:event_datetungayAncestorAdded

    private void datedenngayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datedenngayAncestorAdded
        // TODO add your handling code here:
        Date tu = datetungay.getDate();
        Date den = datedenngay.getDate();

        if (tu != null && den != null && tu.after(den)) {
            JOptionPane.showMessageDialog(null, "Ngày đến phải >= ngày từ!");
            datedenngay.setDate(null);
        }
    }//GEN-LAST:event_datedenngayAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangchitiethoadon;
    private javax.swing.JTable banghoadon;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnxuatexcel;
    private javax.swing.JButton btnxuatexcel1;
    private javax.swing.JComboBox<String> cbmanv;
    private javax.swing.JComboBox<String> cbpttt;
    private javax.swing.JCheckBox ckgia;
    private com.toedter.calendar.JDateChooser datedenngay;
    private com.toedter.calendar.JDateChooser datetungay;
    private javax.swing.JSpinner giaden;
    private javax.swing.JSpinner giatu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txttimkiemhoadon;
    // End of variables declaration//GEN-END:variables
}
